### PR TITLE
ZXCR skimmer has been inplemented for DATA

### PR DESCRIPTION
**Pull request by YujiLee301**

### CODE REVIEW

**Comment by YujiLee301** [comment]
Hi @ram1123 @vukasinmilosevic, here's my latest update towards ZXCR, please take a review. Thanks in advance!

**Review by ram1123 — CHANGES_REQUESTED** [review]
Hi @YujiLee301 ,

You did not started with the latest version of `HZZ_Analysis` branch. This is the reason it shows too many changes than you did.

Please update your branch `ZXCR` with latest changes available on `HZZ_Analysis`. For this you need to run `git pull <remote> HZZ_Analysis`.

<remote> should be my github repository pointer.

**Comment by YujiLee301** [comment]
Thanks, I think it would be a better choice for me to create a new PR.

**Comment by ram1123** [comment]
Move to new PR #32

**Pull request closed without merging**
