### PR TITLE
Added variables to yml file for studying Di and single lepton triggers.

### PR DESCRIPTION
**Pull request by skeshri**
Dear Ram,

I have added new trigger variables to input yml file. I have tested it locally. It is running well and showing the newly added variables in the skimmed root file (check the screenshot).
If you also want to have a look at the skimmed root file then it can be found here: /afs/cern.ch/work/s/skeshri/public/ForRK/BA6427D9-F47F-DD45-BFF3-27F365378241_Skim.root

TriggerInfo

### CODE REVIEW

**Comment by ram1123** [comment]
Are you sure you just edited only one file to get the single and double Lepton trigger branch in the output tree?

I think at least you need to update cfg file. No?

**Comment by skeshri** [comment]
Hi Ram,
I think it is not needed as there is a loop over the trigger channels. So it is fine only updating the Input file.
https://github.com/ram1123/nanoAOD_skim/blob/Anusreevijay769-HZZ_Analysis_2l2q_v2_dev/H4LCppModule.py#L434

**Comment by ram1123** [comment]
> Hi Ram, I think it is not needed as there is a loop over the trigger channels. So it is fine only updating the Input file. https://github.com/ram1123/nanoAOD_skim/blob/Anusreevijay769-HZZ_Analysis_2l2q_v2_dev/H4LCppModule.py#L434

ahh Right. I missed that point.

Just update the name of the file to "Input_2018.yml". Then I will merge this. 

We can just keep one file as it won't take much resource, so it should be fine to keep it as a part of main code.

**Comment by ram1123** [comment]
BTW, could you please try to add one more trigger path for the High pT leptons? So, that we can check everything at once.

**Comment by skeshri** [comment]
Hi Ram,

I have made a list of Electron and Muon trigger paths with higher thresholds.
Please tell me which one should I include. Also, can I include it in the existing TriggerChannel for ZZ2l2nu or should I create a new one?
List of Electron triggers:
Double Electron triggers:
HLT_Ele27_Ele37_CaloIdL_MW_v4

Single Electron Triggers:
HLT_Ele35_WPTight_Gsf_v9
HLT_Ele35_WPTight_Gsf_L1EGMT_v5
HLT_Ele38_WPTight_Gsf_v9
HLT_Ele40_WPTight_Gsf_v9
HLT_Ele50_IsoVVVL_PFHT450_v16
HLT_Ele115_CaloIdVT_GsfTrkIdT_v14
HLT_Ele135_CaloIdVT_GsfTrkIdT_v7
HLT_Ele145_CaloIdVT_GsfTrkIdT_v8
HLT_Ele200_CaloIdVT_GsfTrkIdT_v8
HLT_Ele250_CaloIdVT_GsfTrkIdT_v13
HLT_Ele300_CaloIdVT_GsfTrkIdT_v13


List of Muon triggers:

Double Muon triggers:

HLT_Mu37_TkMu27_v5

Single Muon triggers:

HLT_Mu50_v13
HLT_Mu55_v3

Thanks!

**Comment by ram1123** [comment]
Thanks @skeshri. Now it looks fine.

I will merge this PR.

**Pull request merged**
